language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0

env:
  - SYMFONY_VERSION=4.4.*
  - SYMFONY_VERSION=5.0.*

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
  - composer self-update

before_script:
  - composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update

script:
  - phpcs --ignore=vendor/* --extensions=php --encoding=utf-8 --standard=PSR2 -np .

notifications:
  email: bjouhaud@prestaconcept.net
